# Generated by Django 5.0.6 on 2024-06-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='descrpcion',
            new_name='description',
        ),
    ]
